name: Deploy with Secrets (Example)

# This workflow demonstrates how GitHub Secrets work
# It doesn't actually deploy anything but shows the concept

on:
  push:
    branches: [ main ]

jobs:
  deploy-example:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Show how secrets work (safe example)
      env:
        # These come from GitHub Secrets
        STRIPE_SECRET: ${{ secrets.STRIPE_SECRET_KEY }}
        GA_ID: ${{ secrets.GA_MEASUREMENT_ID }}
      run: |
        echo "✅ Secrets are loaded as environment variables"
        echo "✅ Stripe key length: ${#STRIPE_SECRET}"
        echo "✅ GA ID exists: $(if [ -n "$GA_ID" ]; then echo "Yes"; else echo "No"; fi)"
        echo "❌ NEVER echo actual secret values!"
    
    - name: Deploy to Vercel (if you were using it)
      run: |
        # This is how you'd deploy to Vercel with secrets
        # npm i -g vercel
        # vercel --token=${{ secrets.VERCEL_TOKEN }} --prod
        echo "Would deploy to Vercel here with secrets"
    
    - name: Build with secrets injected
      run: |
        # You could inject non-sensitive config during build
        echo "const config = { gaId: '${{ secrets.GA_MEASUREMENT_ID }}' };" > config.js
        # But NEVER put secret keys in files that go to GitHub Pages!